Resources:
  ProxyServerApi:
    Type: AWS::Serverless::HttpApi

  ProxyServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Runtime: nodejs18.x
      Handler: index.handler
      MemorySize: 1024
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ProxyServerApi