---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Express Application/API powered by API Gateway and Lambda
# Parameters:
#   DomainName:
#     Type: String
#     Description: API Domain name
#     Default: ''

# Conditions:
#   UseDomainName: !Not
#     - !Equals
#       - !Ref DomainName
#       - ''

Resources:
  ProxyServerApi:
    Type: AWS::Serverless::HttpApi

  ProxyServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Runtime: nodejs18.x
      Handler: index.handler
      MemorySize: 1024
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ProxyServerApi
Outputs:
  LambdaFunctionConsoleUrl:
    Description: Console URL for the Lambda Function.
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${ProxyServerFunction}

  ApiGatewayApiConsoleUrl:
    Description: Console URL for the API Gateway API's Stage.
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/apis/${ProxyServerApi}/stages/prod

  ApiUrl:
    Description:
      Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Sub https://${ProxyServerApi}.execute-api.${AWS::Region}.amazonaws.com/

  LambdaFunctionName:
    Description: Name of the Serverless Express Lambda Function
    Value: !Ref ProxyServerFunction